apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.6.1/components.yaml

patchesJson6902:
  - target:
      kind: Deployment
      name: metrics-server
      version: v1
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/0
        value: '--kubelet-insecure-tls'
