apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: istio-helm-repo
  namespace: argocd
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
spec:
  template:
    metadata:
      name: istio-helm-repo
      namespace: argocd
      labels:
        argocd.argoproj.io/secret-type: repository
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
    data: null
  encryptedData:
    name: AgCbsgjsd3ZgVN0qLorzuWTiZFWOvZUK4hxhH9dFOGn3hNJhuTXe6XY7s/1Z/QsPLfp6BRL76hOQRFOVQYm2U4uK/Skq4psYF8z8jvZd9EE59LmzbbqbXMu4c4kk/gS6SNo3GGiYzSl24I0qYfgUoRaGBAwfrxb9HwXmblPiRIXkNIX6aItbiWzmZDXp8Kd1BX0UaN/l43svrGhYg0lfzsyr5/o0CNPZqdHNM/mU0MIJEJLaEUpobhTMlyjIoAqMGjgEDeySnpu+KIjWK7O5AWmQjvxYKIWUOBK2HvahFCvZSFB9is3u/a6vVTmnLadpbjqmfkwlfRy79EZd23R7/8qhT0mgnVs7WQmR85mjquzhVX3LSgkPkzo6BWXlSteNtgadFPcknUmtzQCfTQpVe5aLSddHvSYuU+h1g5pgzvb4XJDGARllYEfH4Bi04qBIXciOsI+1NB43hsYpeO6cA27Og+VzCkbv8hwaSZCzZkRKTqRleNFVLcxTNOB0s1xjOR7pqw7xCR/16AJA+GmMIZ1TTZEEC3zzuFg06S7gpEeUV3nv16BbSK4T1VxzdQC04+BqOtyb3MFejZRgsTrZZGy/R30Lr5mI6fH5PV4gxKeukQoTtmnvhqXx3hq6wFKQILcdhYZCUhqgvmHkNveLCv55VHVY2ei73pw7mNEEN1XktBh9JewShSSzu7mqaSR9p2FD4UHsRw==
    type: AgBEm2+JoFhwjPVCRQ2M3dQp8fUzaIsOLfIkdHvIhxEWUZY4zrBMxZUwZo1i+bgnxxBgPMjX25PPLTELf+WBPikCe2h4/6iscPeElx0jSuQCgACyzhV+si393oAmwsj7GKkIOWQCS6Iq+iEjyoswElOpo0d9sCgfEoNIQ8rrnrE9RaGUOZbiS1A1iXPFNMDhm1sb2Z45yhtwIrp02OJf2p1KxsvuBi4BKGKWiK5JBmHaOyDOofquER31rcXzsOEnUNnJo9B+KX5oQTW6aL6XsMTFrTjs91uSGM7C7l++nSL9aAicX1hwIXuX2svVRRv9SwBnXqXHTeHwVpaOwLtqdT1DFyPZ8iMKN7ans7sRRBDlZ+W/PaCm4HTBtHlq4apE3Ub5w4pZUyPVR58fslVECqCtXMKvIfuPMwee2JRh801miLyKJd+Km66qorDLdiQ/G3vpb/Q9tOTg2yNQbFFr6+SbR4auE360XaptZ1ONIVRS33lXc1QUsnaX+mAKcCrTqiMDSpPkI5DwITMtlEmKM0DnnbIBGxxlUaM1qPPfQuJBmBgyYcbomHFrYDEK5MP4nHpF2wV9oGz/PH2/kQa7dZ4k1i6Az9rCYyi6NhMz3vr4wVgwJ7JanXL9In5n28zvwYdFJ9YB/kK1CFSKDxi7Xf2G38ZGCRmo1PPxZZbEkLBp2Dm8QqFVbINAdqIlaRFeiEE1Zwc7
    url: AgA7v4e9WGm5oPUpRJpUXvYQ25hL0qgYML3OQnkNleUmJdMXKFBJ2lbaWPXEKYpQkr/uF2DCWU1asuZWKSsoOVcUvIls7UDpxmFgGfv9Fd/nk4I4iVSKjXuPifEutMv/iifbxK92hSD3X0KwfLenjuD2FFZkQPBS2RwETEDflA3kl0AVOpaesH1taaO3tDQb94i6taVlrD447IcJsopVgPuM0Ku6E6hdzQ24dRwdRBe6uqlKKbx0AyjR6FelrGY477MIY5b3STrgGSkEZmDD63Pfnn1zA20XrTJAY1XxGWCnB3aVQAvwMPQMFclETlkh37MYxREKD8zi4m3iiQUTdRE9apLv4LPWiuex6Fxa++yHTlxCp1Ynr+jiMgZ58u3XCodq9DVMxQmot33vIYZLDbL6C/ABFV67k4zNYCXWBmB00ZFtDjhi1w19ebtSAZEcwxvrowXp/5XJC/le3LjbooI3Zi7+hUVFIkUmgy23YcmNCstt4XROx6EpNbHT+CUA2+lZqx86n9amnEmYqxnJuz3dEVVZppOWEJ1pSAbju6jOO4NH7fakgZNTHs5liWe5mvsTfJMAi85CBt6Zc6hxGMQlzNq7gMMgERqg0yZNzoH09XuPHdOK2HKbDRkyDcKt1ZEfuyiUd+mpulBKmT9AFsZzUCqdcAiWMrFmDJQQkWBFqwe/sl5BnVVL0FPP0YY9YptrUJRHZhDWfDRj8GTVb5rVpN6Sf02+JA8pF0RRkcjeTUuxeOXTCxrloiqEvpW/NOS0p1I=
