apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/prometheus-operator/prometheus-operator/raw/v0.54.1/bundle.yaml
transformers:
  - namespace-transformer.yaml
patchesStrategicMerge:
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.54.1/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml