---      
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prom-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tools
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 31.0.0
    chart: kube-prometheus-stack
    helm:
      skipCrds: true
      values: |
        nameOverride: observability
        alertmanager:
          podDisruptionBudget:
            enabled: true

        grafana:
          enabled: true
          defaultDashboardsEnabled: true

        kubeApiServer:
          enabled: false

        kubelet:
          enabled: false

        kubeControllerManager:
          enabled: false

        coreDns:
          enabled: true
          service:
            selector:
              k8s-app: kube-dns

        kubeDns:
          enabled: false

        kubeEtcd:
          enabled: false

        kubeScheduler:
          enabled: false

        kubeProxy:
          enabled: false

        kubeStateMetrics:
          enabled: true

        nodeExporter:
          enabled: true

        prometheusOperator:
          enabled: true
          tls:
            enabled: false
          admissionWebhooks:
            enabled: false

        prometheus:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      allowEmpty: true
