---      
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tools
  source:
    repoURL: https://github.com/justinzamora02/gitops.git
    targetRevision: HEAD
    path: observability/base/metrics-server
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      allowEmpty: true