---      
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-application
  namespace: argocd
spec:
  project: deployments
  source:
    repoURL: https://github.com/justinzamora02/gitops.git
    targetRevision: HEAD
    path: demo-app/overlays/local
  destination:
    server: https://kubernetes.default.svc
    namespace: testing
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true