---      
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
spec:
  project: tools
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.13.2
    chart: base
    helm:
      values: |
        global:
          hub: docker.io/istio
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      allowEmpty: true