---      
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
spec:
  project: tools
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.13.2
    chart: istiod
    helm:
      parameters:
      - name: "global.hub"
        value: docker.io/istio
      - name: "global.tag"
        value: 1.13.2
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      allowEmpty: true