apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    name: istio-system
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: "HookFailed"
