apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: bitnami-helm-repo
  namespace: argocd
spec:
  encryptedData:
    name: AgAYm3n9m52nD6P6GZY9WPke+oc6tPVQjA4lwF5R/dkFmkDNIb/6IQFqWY64lcTjzhbhd3eKD1fwNU6LKRi77CIZXdaAT9sBuRwghNdCj8HsgnbK+cYb7Ekc/wG7niseCSxQlmxnbQWudM2AzHlYoHdBKmBkeAzWdoQR9N1B6HiUonvjAZPI/Xw2irBOqooUq40eGrY1aVXYG3oN8XhasxOJEnj6AhS7ZPyZgJrjQ40aMPZFTVuxpSLWRVcK0t7EN60W+l4R5bl0ivgIRD1YnQ4Ebx/jUDCgwg3eS99Kh+Dmy91a6NYRPvJWt2Fc5C55X7NkqRv+RFcMXf7Z6QJqrfTuVkgVoCUf39FZWJSQfrYJRQiXGUP8TAFoqHSW9Rm90K/4F2/ptyioOlCOHtB+eRh5pTdD2NcBM6jDEiDdWf+W7s3wIVFattTR64JEVisjibuYPYqydqs+cwbZ+GkNznyVAa6nTl8NJVNTTFXWYuwgCjbyhWr7HHeZLJuK7OERmr1fEMZ8eGucY/jRr/hQRk9jytGFNSkaN/IFyqZNhcyEUtU1Y/cD7N6FwO5RZBySYcy8UfoLr108sG0Ydkx7EbZChLPh5BjLIADQ/O6vFpJCyazrqBSXXwX42ZJfdKVbwbB3u9GK5vWdXFPdxATKAWaA57e0HBMRH4Es6F5nLwV8y6B58jBB8zmAcd22B5Ld/ax7ZtE0JrZv
    type: AgBoJudsincN8jzuo9B0EqFKc60fnaLiyaSDHmOhl8XI8oTybwEa4mKe3tsiJvm/AbHiZ61mala+jMIXpSQb+fzkU9gVQkSk9ly6iwxQ4QFIin5KFqFVBMmk6Oja5zFHWo0hRONfa7sE9H9Xdq3h01OMEnCEee0aNSih0/j6o1GOm5MLSKA2/WERDDY4eFrdc0yH+ph61bb5MrEc0Kf7rhyhrQNu835eX+eRyo0c/pVkeuDjkuKDR0TjdGZ1waq+mstwl3+ZEVQjY15CCMA5KuNlsv0TBNgw3o2Ej0MP9OCYJ3HEOydJw/Yfg3Ly1q1D6d1Du5e/RsKZXwRykC9Z4LvMmmIY12Pgd3fiVHSz6sFi7Fm44Hf+2Rp09DDA8u2sX/6aMjGM8wmnAmY4yxMrQ/4DBR3bIzZN4pAn7XSUprRDINAZ4DR2Zo6tMlq20sqvBEmCFRkrXEJ/5lD2cv1AhzkRB/JMbqttiNoiweubwKNWtbxFZLFVNJMzTpPsE5EMB7+JEyNovdh5hm7inm1vcRUCv5H1/H26b7NwBTgqsv31kPrQ+LDY+KRik6qKQgjW9AaVL+Aox+n0QIQ+mWYNNp4wtGYJIc0RZiPEG7YVzsIsvVXjAXakKD3i9efTYjM5OOKh2Eiy6uXNBX45Hsl9IM3pFPgUoagwaf3mGrhaapMv5mP9x6VDiVSTCRT5pMtBV8qhOdc4
    url: AgCAvXPom8WV36pQsoXhbblj86YL1ZKxThieE4fivLiZcCnw2XP8ZEy94sk0qMErE8Hojv+AhyOho0Md4dXWbXzUA6D2VAlRXGc5bBuxkcj6ftb64XGnn6uvvbVvU/Milgn/fWZzD1iGQ3D1Q5NNazyQvwaVxlvQChiKraV5+uI0SygThecdNp18wxgUkTAZFE81BPcVlLvEinb1Gw6hTFHtWwotV4IZVl4sEWcgsbajO7KU//krWu74guD9H/8QeAy7/a4xorISrIdAYXIHSbuLl1pZ4GaaSb+gPEJfl9iCjGbjslabn06/qkNYSgVhlKloBwIcWsR94yFlRx2zPX+C18tfJc6wO56NBaT3N+zp6O/XasUxqXgbRUwxZ6h/ICmiTQCYB62WKjHQBI/Q7ZcJD6mkMqR9KWGJM11qcFDleFz9ktCq3adClgq/QLzzT6PN+Tl4FMU3aHgy0zYaNkzqrWCwYPTgrrgboJR5rjqVGLzfsTqQ7QChWiURWe3BKU9E5u3khhAd3WioQP/o9Vb7IaIOrIoRnHBA7jkgBiza2Vm4i6u1USeKdG3tVFIU2YgVoH4nLgjk3Bds/2frDV5AgNAUztXlYWCJ5kR7lNo1NlhbzedjFQyD4OdJq4DPwL94Bq9QPssamNlsvKzz+zeWNGh3ryVLbUCrefqKOSaA00IXiiHohkWAVg3fnFn6HpZ0JP9HUNxsWotQYER7p/ahPxs+OoYL7MFLD42FtRYkf4oW
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: bitnami-helm-repo
      namespace: argocd

