apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - testing.yaml
  - repo-istio.yaml
  - repo-prometheus-community.yaml
  - testing
patchesStrategicMerge:
  - argocd.yaml
  - deployments.yaml
  - tools.yaml
