apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../../common/overlays/testing
patchesStrategicMerge:
  - argocd.yaml
  - deployments.yaml
  - tools.yaml