apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: istio-helm-repo
  namespace: argocd
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
spec:
  template:
    metadata:
      name: istio-helm-repo
      namespace: argocd
      labels:
        argocd.argoproj.io/secret-type: repository
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
    data: null
  encryptedData:
    name: AgBKnLboTQmYFj+j7HF2YcjH9m9fPQaKmvwV+QlsWnBab5P8KnnAUvnqLS4PT6XapBgkKryysNs53zemTGS5+LHKDC5tI/vKYo87pVOuqIjSAHsuRDP6IvB381N54Op9iFJ2nyIUcNRs4a6V1E2QhDEGSEsrSfJBjoBh8okRiF/LGGw/Sogv40/zgvubsJFa8Pb6UJN7DE0j+7p7qvHyipG21N+1GFGa+dXQ/DiixsKvfDSo460n1QnAltS/3wpBNiX4ixdxdo8Hy3cNbiJw01WVDg4a+gfmpp1274I5TashoAy87DkAq3AwRAXBEXA3QSRNgvbzyJJl38TvQkeGHG054L+ieNsdN42T5tM5pRwAArvEv8vP9P3KN5QXIMghvJkwrmP8DeZ70aFq5I3OI8yySiqNYcvdjsdnboUjX2P2TuYhmtUgkBM+72gJgO5s/vumJia1M4q60dOuOrKCzuK/+uKPVSXpSXFjVuFh9GBjkEgTkLWGZIlnzZ7C54Z1t6m0ub7dBH0eJ+0FXoI32YEMLMznFAARV+NttT71kkuAEO1EUbS2nfM976kdR4RWcBy6pwu2kRdJ1MNnFFR2cNnK30bNO01JXc84ppdlxmVoBlsOjPtQHUE2t6EX/ycSewV5ziTLD+Ws0N+hXSZPYIED4Wo43+5S7yzcB23MiPWbSUOnV6VCPLCU6jHssWFHqD2SsAsODg==
    type: AgBX3s/ew1GE1duyqnA/+LGIUt2cJKgQkXOQMWpHrowp/vMkNcTljG319qxY4mtRf9VJ4sKsyErysWsm96AYDqlqjZn1CV0I1yvEHEMrjs8mHp8uJZ723ARPAQ6We49rPU+bSmRjc+ZCMTqMbVhYIQGjkczrVP6TnSTk+CdnCphHF/tP4vfaFRxgtlbsW+Vvl6NR6wseMaGShvwxsGKQP3vl3zS//Gz2uKM0UrjgnvHPDyT9diBx6Hw23tfjtZkGzvd7e42LCzyjyzjsG3WCJWts87jVj0JWMNqNiBuk7VQZHcBJcXjGSSZH9Dz17Ca7dkPtZX4nDoAZRFqTiHITpv+If1ZjDTuHQ8mh/2DiYr6YKeBrN4OpjG92jnZAaXWspl77TlNlN7JpUhyRPzyPNhbz8MqbYAOK4N6HFG4f/i2FG0SMUi4aKT2NZKRE8sA9Ks34ly75UZhEpFolUdte9r9Yj9ZHImspe1GPY2BtSi96myGEdjmx5IahMlr6taDTDztIcwpjm63maaSBomad+tiWentQ77hFog7UVZ0PrkR/5Dqg6kotCUKOGGwVmIG47dSWJmkTx0XWPMiKT7L4wBmeCbZHQjTup5oDQkxNUTYx8Rmv8BD3TF4Bt5KByxAGyD9Y2C8MgNBNxAtalWfwtb6EA7jRZ1g4cUyiCLxZUIDqKoahdn1M7H2K61V+VZhzTuXjAIWr
    url: AgAymnSxVVJD7k2BS8UI1GS9YN9Z8xaIZB+u+ZSPDru9ZRLAQIgxipqdyT8ISxDFzAoA6xxbUqmUkg436Kj4Yo1GTf7eZmG6Myu8TpMfOu8IzRZ1aKwnyxVWabAlJuN2SvBeuXSxiIUWNRp2pgMwl9NOwm3Ku7l35juuJ7YVwCFNG+qXTx1PmGpjJeoh/3DUc9FittknDC3QlPYaqCrHoMh4x2zvklynPJB7gXMK9z1ovcr/tQJPKn3j8RfysEhydpE5zDWEqRB6DCBE6aYnWQLgsRSfG3DcCGlTwXhr5KYgeBIABGR7qCyHa9tJXvfNerikwGz80avscb550eO08Sg3QdXLlPd7cN6EC3XVXJF+/RH0Kb/2SWwAyVXJnkWEs3jXwur4pvvknVD6kLK1rHRmS7DcKS0tniS+QhxLG3uM0p3guqkCULqUZp5oghi584pANkcXRrpPUuFIPsZrZva7camziVg27nzeMuyrwWuMryIGCj+fUY+uZVpnwTLgPcIKa3/+wbopKF7ujXK0Y5W143AdiYBG4aX/88W6xoJjsMiMRhl+lHKJvUkxBLX1H3U3qLLwl0WKPIJGm8cC2a00QHHfQ/ZO4bAdTO5Ik9dQyH4r+BAOobBdYgLkuahJ+gKzFEvXN7aEfYqCrcG/derz0i6cQpMT0vyxq48l1att5lg6cUsVDvPycHNoJAnecJEKFWGd9whg6dTD0JkxRfX67prEiLX04H78hERykEGgxnpJohESN7ZZHV5qYTmdD7NKEF4=
