apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- behavior: merge
  envs:
  - .env
  name: cm
images:
- name: justinzamora02/nodejs-demo-application
  newTag: 025b21ae22bfb87788438f546ca4b8d51ba7c42d
resources:
- ../../base
- ../../db
