apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../db
- network-policy.yaml
configMapGenerator:
- behavior: merge
  envs:
  - .env
  name: cm
images:
- name: justinzamora02/nodejs-demo-application
  newTag: 6ce7490b32a58840abd1fe0de76840a2e9d7a667
patchesStrategicMerge:
- psql-secrets.yaml
- secrets.yaml
replacements:
  - path: replacements/psql-sts-svc.yaml