apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../db
- network-policy.yaml
configMapGenerator:
- name: cm
  behavior: merge
  envs:
  - .env
images:
- name: justinzamora02/nodejs-demo-application
  newTag: f7b45c9ff2437a940d0502dc48a788b4e1ac1acb
patchesStrategicMerge:
- secrets-test.yaml
- secrets.yaml
