apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: cm
    behavior: merge
    envs:
      - .env
images:
- name: justinzamora02/nodejs-demo-application
  newTag: a3548df915c412c753d953628c422893b3e6dafb
resources:
  - ../../base
  - ../../db