apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../db
- network-policy.yaml
configMapGenerator:
- behavior: merge
  envs:
  - .env
  name: cm
images:
- name: justinzamora02/nodejs-demo-application
  newTag: 8746150cebdb9799c6753e8b66049f3674a3d243
patchesStrategicMerge:
- psql-secrets.yaml
- secrets.yaml
replacements:
- path: replacements/psql-sts-svc.yaml
