apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: psql
spec:
  ingress:
  - ports:
    - port: 5432
    from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/instance: demo-local
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgresql
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: app-client
spec:
  egress:
  - ports:
    - port: 5432
    to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: postgresql
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: demo-local
  policyTypes:
  - Egress
