apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: demo-app-secret
spec:
  encryptedData:
    DATABASE_URL: AgAYw7pq+UQL4EsKTjQ+kJgTA4c6Q9GjxQzv5QIq9gZcvUJWGkJcSc6g1M3FBjV2gc8n8HkSSgkgPZ8BtZmejt1imnM29tbKZ7Mvqip4E8isAD8maaAZSqEUQjecUoX4LSqGvSSmoBjPlnuUJ3Nlm+BdpPq0cIljTiEkbUJc31pHLT/8wWbfCQhPlENQ+CmPUHKSCxSQO2VZEgF6uKaT8/tEz8Hf0ZYF5dNeAb9Ods6Zu5cm+rDkdjSlHjEvDXiLwVLo7/FWIrvdOerXfpVlqKmCiKwnTtz31Pd1LZG2Hxo6jzQuy4XGi9ppIIjoty6t7anHf3tMVfs7MFgJ0I0nmC1/Eftm4yqw9EHddYmqQLxSrbWxHhAl+GSdFj4EkRoQYZcrf+DE23Q55MK7D9g6Bz+Fq2fkk7PcPgUl5QPN+nuWFerLur5vhyywVfUmp5fBKLX7N2gEoY2tHghwQl6PIEwUF0cgILw/94wESJe2w9ge69myWWJsMwyaHmGrPmYEg0cUuc1MpDIRdMyrO357jyUeKIQe3i4wuLPf1grWX1254GlwiGR0uDPNWlToArSB3loqkSpZTsDNpqeeGAJS9eXxZKgh6/e5ySb28wOHYB9tmu6MLU54gMDrp4Ke0u4VRLlCjUiQ7DPEvE0QEVc0CHfnhAQR+K5+AyolNetNUrtT1+K5GSQIo7QxKXs98GqxzB+bhHxaxeXvXDoHceFvwTfMk6baR+Uq+7Z9dWTmQJnU89G3EY2f48RCQ/rb4q5zTMqYSbH5Yd0U8GTp1DiLSOOrJVSN
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: demo-app-secret

