apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secrets
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
spec:
  template:
    metadata:
      name: secrets
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
    data: null
  encryptedData:
    POSTGRES_PASSWORD: AgAoALuNnT2PLTSFK3Lms7xuxVNBdOeushb3MhJWC1EL5dJLAJL8Qg2yP3oMdkl4b7pFGoQ/KvW02WXsOLOOjnRUHTJuUOGb/EFFmT1EC4tQqWMp9BzXkQi1N3uPVvA+ZPbJwAC/rIcRcpbw/c/h3pEDgBQSuVk1EoQSl9X0MOt3is+JlcMXaokxrY5EIdHMNeFKAO9U6QyD5siwGtUePaJuHU1oD6b8Gejk+Noj0reKJEbmKGlYbfimPyUMcg6ERRsscYGBIAB2XgHOb2oOJetzOtdIpewh7RO1/2tLP7aXXQzHTtMgzu12gOTjlySs8c2uJ3zSXXTdkkCAU+nNy/5XkBGToa8u4M28pX3oC4V1qbCV+BWheFLDreyJSzJvocUtSNH32lxqSlOAfKvnMgPKKcVt3WKN97XUH4W7BJHeuPWwZihZxmisATJgLAUlDrP3fEFAH9AfOqKRpVkGk5KWD+Z4UnEh2+HqPxC7/Dc7idDWPoqG1XUiAoZhrVEkF8K0F8kVookq0fyxS+Z+ceiiSVERH6L6aB9+HosxeJVK9O7MFKsMAnEQG2Pns0w07GmxqOs5VKAzGHCDKoIvXw7d/LHyEoqX/aO1ZXfdQ8uM8HdLV3FMoE2cVolKS9QrnxfS/Gz+1y9mQW3NSkroJV8+WV7ZoNBkInBZLXiEo7UJSIdD16eNEqKWc/mLQ49HdYitjXCbEOAZEQ==
