apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: deploy
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook: Sync
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploy
  targetCPUUtilizationPercentage: 50