namespace: testing
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service-account.yaml
- service.yaml
- secrets.yaml
- jobs/db-migrate.yaml
buildMetadata: [managedByLabel, originAnnotations, transformerAnnotations]
commonLabels:
  app.kubernetes.io/component: backend
  app.kubernetes.io/created-by: argocd
  app.kubernetes.io/instance: demo-local
  app.kubernetes.io/name: demo-app
  app.kubernetes.io/part-of: demo-app
configMapGenerator:
- name: cm
  envs:
  - .env
namePrefix: demo-app-
configurations:
  - kustomizeconfig/name-reference.yaml