apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
buildMetadata: [managedByLabel, originAnnotations, transformerAnnotations]
commonLabels:
  app.kubernetes.io/name: demo-app
  app.kubernetes.io/instance: demo-local 
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: demo-app
  app.kubernetes.io/created-by: argocd
configMapGenerator:
  - name: cm
    envs:
      - .env
namePrefix: demo-app-
namespace: testing
resources:
  - deployment.yaml
  - service-account.yaml
  - service.yaml