apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: deploy
spec:
  minAvailable: "80%"
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-app
      app.kubernetes.io/component: backend