apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: deploy
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook: Sync
spec:
  minAvailable: "80%"
  selector:
    matchLabels:
      app: demo-app-api
