apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  type: ClusterIP
  selector:
    app: demo-app-api
  ports:
  - name: http-web-api
    protocol: TCP
    port: 80
    targetPort: http-web-api
