apiVersion: v1
kind: Service
metadata:
  name: svc
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook: Sync
spec:
  type: ClusterIP
  selector:
    app: demo-app-api
  ports:
    - name: http-web-api
      protocol: TCP
      port: 80
      targetPort: http-web-api
