---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: deployments
  namespace: argocd
spec:
  description: Project Argocd locate, lock in argocd namespace
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---      
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deployments
  namespace: argocd
spec:
  project: deployments
  source:
    repoURL: https://github.com/justinzamora02/gitops.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      allowEmpty: true