apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesJson6902:
  - target:
      kind: Application
      name: demo-applicaiton
      version: v1alpha1
    patch: |
      - op: replace
        path: /spec/source/path
        value: demo-app/overlays/local
