apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - statefulset.yaml
  - secrets.yaml
buildMetadata: [managedByLabel, originAnnotations, transformerAnnotations]
commonLabels:
  app.kubernetes.io/component: database
  app.kubernetes.io/created-by: argocd
  app.kubernetes.io/instance: postgresql
  app.kubernetes.io/name: postgresql
configMapGenerator:
  - name: cm
    envs:
      - .env
namePrefix: psql-
configurations:
  - kustomizeconfig/name-ref.yaml
