namespace: testing
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: testing
  target:
    name: namespace
    kind: Namespace
    version: v1
