apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: testing
patches:
  - target:
      kind: Namespace
      name: namespace
      version: v1
    patch: |
      - op: replace
        path: /metadata/name
        value: testing